#!/bin/sh

status="$(nmcli general status | grep -oh "\w*connect\w*")"
ssid="$(nmcli -t -f active,ssid dev wifi | grep 'yes' | sed 's/yes://')"

if [[ "$status" == "disconnected" ]]; then
  printf "󰤮  Ops!"
elif [[ "$status" == "connecting" ]]; then
  printf "󱍸  wait.."
elif [[ "$status" == "connected" ]]; then
  strength="$(nmcli -f IN-USE,SIGNAL device wifi | grep '*' | awk '{print $2}')"
  if [[ "$?" == "0" ]]; then
    if [[ "$strength" -eq "0" ]]; then
      printf "󰤯  $ssid"
    elif [[ ("$strength" -ge "0") && ("$strength" -le "25") ]]; then
      printf "󰤟  $ssid"  
    elif [[ ("$strength" -ge "25") && ("$strength" -le "50") ]]; then
      printf "󰤢  $ssid"
    elif [[ ("$strength" -ge "50") && ("$strength" -le "75") ]]; then
      printf "󰤥  $ssid"
    elif [[ ("$strength" -ge "75") && ("$strength" -le "100") ]]; then
      printf "󰤨  $ssid"
    fi
  else
    printf "󰈀  LAN"
  fi
fi

